{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-eml
  version: {{ version|replace("-", "_") }}

source:
  fn: EML_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/EML_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/EML/EML_{{ version }}.tar.gz
  sha256: 2b38cddb6605658e924f4f8752c34e1c59d13b01da8a71edfaa1aea7927a81c8

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-uuid
    - r-xml2 >=1.1.1
  run:
    - r-base
    - r-uuid
    - r-xml2 >=1.1.1

test:
  commands:
    - $R -e "library('EML')"           # [not win]
    - "\"%R%\" -e \"library('EML')\""  # [win]

about:
  home: https://github.com/ropensci/EML
  license: FreeBSD
  summary: Parse and serialize Ecological Metadata Language ('EML', see <https://en.wikipedia.org/wiki/Ecological_Metadata_Language>
    for more information) files into S4 objects.
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
