travis:
  secure:
    BINSTAR_TOKEN: q9/RO5YnHGG/M+dP+Sc0rUxlchKjp896J7p3oEQ4JuYcMDpjQbxOd25QKpCfcnCl/4BZs6XMizMbE3t2dkYUfE0cRO8flPzXoDDh0Y/ApKF9Q0Y5sfCwAEyT2e134wBcCQc56C5a529TsI+nPDwI9n3hP24eZBTRBUPSlXJ7/0392DKMbLFjNQgXp2/bl437Cgc8+zVD3czN0961U9/m7AYj5ipgT7wpKeFqmlsHPRPdtKjlUCvcn6DtP4ClmfyNLSpPec5hbH8Hpbji4uP1n0c77w9Zag+3YvOX0s1zVdj4ZawaDRkuHHw6v58fB00iFqYPHfj5J+4Kud3cIKLUD0gPGQr2xtDk3hDjJVk81GdrmZnrrEKZm7aGB4fchuwGfa65bWI6/EBv2cSIXDrPIm4oVPqWSZ/8gOoPv7m7CK/hgynYiDpelWUunM+5Rnlki0gzCpcLRQbhxRDXlh/TNxgS+zaV8SHe2zNbUZd/eJU8fXzr/1glexdSatHqbUevbNrBiBshFKTyOIUffvkRsT0D0CIS8MKF2hdTxb9/s5kQc4EEzmuCevrxBmc2TUxa3cuJr0P7+3/kaQ95l8QTFHusnGhOeh241jLhR+/Yivs5zu7NGzg5TGTBFU2mHiEj7gxaID7BWDLnaFuzcXXhmapMBpPUCGIJ2mBB6BwJ5H8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
