appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bfzx3ggkIOYrjKS0EW5NCAxUMcnfTWI6HpsOBC9UX8eFFVqyXUiWNrrtglVUOItUp7knKP3ZhtMBkmlpEOdexkmF2SJco4D2raJ7Un3hjdfcwpxohk5wAVchGZWqBPRJY2DGXehT6TB34US8/kOJ+xrK26qjRoO3pY97lI/XcP35nZbWM6jw6oWMOvm9R42bjn/8UwQWTkJZygL60AgJLSCrBXOIXyduGJ7wZaftLAEq3CB19Ugiw+u8WqpzqZn5JuljjbGvyB7KQhgXb5V751dh/e/+EjoDyXpvRjXpssV/LPqUrNgNSqB2dn2kr9zivQkhUEjyaLCWaHw10sg9EoZSy+7sJ8i173gxyPhc/zOMvUM87nFJuCJ+45QGfp63+vtHIhHTi1bew0UHL0o+f21SQrhNV2aCsNWEe819w77xMkZgz8/EkAtmoeCqvHmW7fg/01P6K8zlfWH+TBFoypzxu9OBftUfTsMAYgwY1uvZgIe9fyhNyBHTKlkW/V/CScp9BGmeyCPWwkYvC/MrnWjVUp6P5wm482eDBG01K9i3Z+dvpf6ZrMXaaiPbCfYx9n04pLvkaVwwyjqaZgM2worWmH8gxig57bC47dEUadzpH5RVDHOVc8HRmaesAnXJe33OEfmstSxm/DdX9vAsU7Vjpg4Nmnp647MnN+YFZaE=}
